# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [5]:
import numpy as np    #Numpy is imported
x = np.arange(1,11)   # The range between 1 and 10 is printed
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [7]:
a = np.zeros((3,3))   # this is to compute all zeros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [12]:
a = np.linspace(0, 5, 10)  # the difference between each number is the same
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [14]:
a = np.eye(5,5)    # to compute identity matrix, it must have values aside zero at the diagonal
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [25]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [258]:
arr = np.eye(4)
print(arr.shape)     # np.shape is use to get the shape

(4, 4)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [89]:
a = np.arange(16).reshape(4,4)   # to shape a 1D array to matrix 4 by 4
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [57]:
a = np.arange(16)
a.reshape(4,4)
print(x.dtype)   #x.dtype to get the type of the array

int64


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [67]:
a = np.arange(2, 101, 2)      # The even number between the first 100 values is computed
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [75]:
a = np.random.randint(10,50, size = (6,6))    # Random number between 10 and 50n is generated
print(a)

[[15 31 42 40 20 42]
 [19 43 12 29 15 15]
 [19 20 13 29 10 12]
 [41 33 44 30 21 35]
 [19 40 20 48 16 33]
 [35 26 38 27 27 25]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [83]:
a = np.array([[1,2,3], [5,6,7]])

b = a[:2, 0:2]                    #slicing an array out from an array given
print(b)

[[1 2]
 [5 6]]


## ---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [91]:
a = np.array([1,2,3])
b = np.array([7,2,8])
print(a + b)                       # Adding the two array element-wise

[ 8  4 11]


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [262]:
a = np.random.randint(1,50, size = (6,6))
print(f"mean: {np.mean(a)} ")                 # The mean is computed

mean: 29.805555555555557 


In [263]:
print(f"Median: { np.median(a)} ")            # The median is computed

Median: 31.5 


In [264]:
print(f" Standard deviation: {np.std(a)}")     # The standard deviation is computed

 Standard deviation: 14.721147759533721


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [266]:
a = np.random.randint(1,50, size = (6,6))
print(f"Maximun value: {np.max(a)} ","\n")     # The maximum value is computed

Maximun value: 47  



In [267]:
print(f"Minimum value: { np.min(a)} ")          # The minimum value is computed

Minimum value: 1 


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [268]:
a = np.random.randint(1, 20, size = 20)
print(a)


[ 3  4 12 13  4 12 11  6 14  2  6 18 16  4 10  5  8  7 18  7]


In [269]:
print(np.argmax(a))                    # The index of the maximum value is computed from the array

11


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [270]:
a = np.random.randint(1, 20, size = 20)
print(a)


[ 1 14 14 19 10  3 12  9  2 10  5 15  2 12  8 14 16  4 11 15]


In [ ]:
print(np.flip(a))          # The element of the  array is reversed

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [142]:
a = np.random.randint(1,50, size = (3,3))
b = np.random.randint(1,50, size = (3,3))
print(np.multiply(a, b))                    #  The element of the two rray is multiplied element-wise

[[  14  550   48]
 [ 792  252  588]
 [ 920   28 1748]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [144]:
a = np.array([2,4,6,8])
print(np.diag(a))           # The diagonal matrix is computed where there are non zero values at the diagonal

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [163]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[1],[4],[6],[7]])
print(np.dot(a, b))            # Multiplying two matrix row by matrix not element-wise

[[ 55]
 [127]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [272]:
a = np.array([[1,2,3], [5,6,7]])
print(a.flatten())                # Converting 2D array to 1D

[1 2 3 5 6 7]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [277]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
c = np.vstack((a, b))    

[1 2 3]


In [274]:
print(b)

[4 5 6]


In [279]:
c = np.vstack((a, b))            
print(c)

[[1 2 3]
 [4 5 6]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [280]:
c = np.hstack((a, b))      # joining the two arrays together horizontally
print(c)

[1 2 3 4 5 6]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [282]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [283]:
print(np.split(a, 3))         # spliitting the array into 3 sub- array

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## ---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [284]:
a = np.asarray([.656,2.778,3.747, 4.2243,5.1234,6.8976])
             

In [285]:
print(np.round(a,2))    # rounding off the elements in the array to two decimal places

[0.66 2.78 3.75 4.22 5.12 6.9 ]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [286]:
a = np.array([1,2,2,2,3,5,5,6,7,6,9])

In [ ]:
print(np.unique(a))                  # Printing the number that exist once (unique element)

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [199]:
a = np.arange(1,20)
num = 10
a[a < num] = num       # Replacing all etries below 10 with 10        
print(a)

[10 10 10 10 10 10 10 10 10 10 11 12 13 14 15 16 17 18 19]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [287]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [288]:
print(np.cumsum(a))     # Finding the cumulative sum of the element in the array

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [289]:
a = np.array([0,2,0,0,4,5,6,7,8])
print(a)

[0 2 0 0 4 5 6 7 8]


In [290]:
print(np.nonzero(a))    # printing and excluding the zero's

(array([1, 4, 5, 6, 7, 8]),)


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [291]:
a = np.random.randint(1,20, size = 20)
print(a)

[17  5 14 16  3  4  5 12  2 11  2  6 11 16 17  4 15 11 18  2]


In [292]:
print(np.sort(a))   # generating random numbers and arranging in ascending order

[ 2  2  2  3  4  4  5  5  6 11 11 11 12 14 15 16 16 17 17 18]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [215]:
a = np.array([[1,2,3], [5,6,7],[1,2,9]])
print(np.sum(a, axis = 1))

[ 6 18 12]


In [216]:
print(np.sum(a, axis = 0))

[ 7 10 19]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [259]:
a = np.random.randint(5,20, size = (3,3))
min_ = np.min(a)
max_ = np.max(a)
a_norm = (a - min_) / (max_ - min_)

print(a_norm)

[[0.07142857 0.         0.5       ]
 [0.71428571 0.71428571 0.        ]
 [1.         0.78571429 0.14285714]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [229]:
a = np.random.randint(5,20, size = (3,3))
b = np.random.randint(1,20, size = (3,3))
print(np.dot(a,b))

[[308 218 221]
 [338 153 351]
 [400 288 301]]


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [231]:
a = np.random.randint(1,20, size = (4,4))
print(np.trace(a))

45


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [235]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
temp = np.copy([0])
a[0] = a[2]
a[2] = temp

print(a)

[[7 8 9]
 [4 5 6]
 [0 0 0]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [236]:
a = np.array([1,2,3])
a_vec = a[:, None]      # this is create 1D into a column vector while that of row is [None]
print(a_vec)

[[1]
 [2]
 [3]]


---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [240]:
a = np.random.randint(1,20, size = (3,3))
print(np.linalg.det(a))

361.99999999999983


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [244]:
a = np.random.randint(1,2, size = (2,2))
from numpy.linalg import eig
w,v = eig(a)
print("Eigenvalue: ", w)
print("Eigenvector: ", v)

Eigenvalue:  [2. 0.]
Eigenvector:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [248]:
a = np.array([[3, 6, 7],[2, 1, 8],[1, 3, 7]])
b = np.array([[10], [11], [22]])
print(np.linalg.solve(a, b))

[[-9.63461538]
 [ 2.42307692]
 [ 3.48076923]]


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [253]:
a = np.random.randint(1,10, size = (3,3))
guassian_noise = np.random.normal(1,5, size = (3,3))    # (mean, std_deviation, shape)
print(guassian_noise + a)

[[ 4.88988042 14.7714776  -3.98398392]
 [ 5.92779536  1.63495011 -1.84104106]
 [11.16427245  7.46031328 13.62198628]]


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [256]:
a = np.random.randint(1,10, size = (4,4))
print(a)

[[6 8 4 8]
 [3 4 8 7]
 [4 4 8 1]
 [7 4 5 7]]


In [257]:
print(np.diag(a))

[6 4 8 7]
